name: MPAccess
version: '${version}'
main: network.magicpixel.bukkit.MPAccess
api-version: '1.13'
authors:
  - PlaidMrdeer
description: MagicPixel私用插件

commands:
  mpa:
    description: mpa command
    permission: magicpixel.command.mpa

permissions:
  magicpixel.command.mpa:
    description: mpa permission
    default: op